language: node_js
node_js:
  - '8.7.0'

script:
  - npm run build
  - npm test

notifications:
  slack:
    secure: S2aYgu/+1FB20jIhMn89bVeHDmi+ybFomF1erHjU+ZlNoljDt92w5QEgpgdHK/nqnJNFYa/E9CMLr/usw6lC+cF0iODgsngZhWs1+9WySo+gCB0SdZDEpoJLLi3Q/aLr85DlO7rtiezujZcyCrb6AZRJNVbyzzLR4BCAaBHBIHzzCOjPqDIe45VH/vxh1Y6f5GMohVQOU5JumPWaqg6CMUb1o8F6B8G0QbomkSCOES8tRE4cZSDzMInFnOnehHlV/GHdJwdmvAAuMo7M5+RcuujCZyZWZLSo7Ogfv85bzGEOl4Zr6K5vGmhFjoYiPnQyh8hcS/kmuQ7HF00aLxfo9tCtr5dhwaOEjlbB/Poy01As4PbAwQ2mGPJ53f12LGn+YP3IVjihFkWhgYzLUqew1dYLBB8/qGxK1w+eii7CRp/WyMfDLlu89mZjKZc2B/E/WOuDYnKIHkeNxY5i0rZWw9vWx0lanPKlqBeIOcWh9DPxtnseoCiKqSLHdumweyG/Yjhe9DZB0f3ESododU9FBCV6NysxS1v6zi3o5puihO406ysAXzUQCAx71bXmooXuAvRLoEsa0ryDH7uQyrjpWqT1itI14P8CUsntCkDb0C6nxZUOu216XMjBYdQTBOd5L4y5Kj34A+p182srJdeLf6hQ0vsdqHs9VagPa5ODs6w=
